App\Entity\History:
    type: entity
    repositoryClass: App\Repository\HistoryRepository
    table: history
    indexes:
        fkey_history_lunch_option_id_idx:
            columns:
                - lunch_option_id
    id:
        id:
            type: integer
            nullable: false
            options:
                unsigned: true
            id: true
            generator:
                strategy: IDENTITY
    fields:
        slackId:
            type: string
            nullable: true
            length: 128
            options:
                fixed: false
            column: slack_id
        slackName:
            type: string
            nullable: true
            length: 128
            options:
                fixed: false
            column: slack_name
        date:
            type: date
            nullable: false
    manyToOne:
        lunchOption:
            targetEntity: LunchOption
            cascade: {  }
            fetch: LAZY
            mappedBy: null
            inversedBy: null
            joinColumns:
                lunch_option_id:
                    referencedColumnName: id
            orphanRemoval: false
    lifecycleCallbacks:
        prePersist: [ setDefaultDate ]
