App\Entity\Tag:
    type: entity
    table: tag
    uniqueConstraints:
        tags_name_unq:
            columns:
                - name
    id:
        id:
            type: integer
            nullable: false
            options:
                unsigned: true
            id: true
            generator:
                strategy: IDENTITY
    fields:
        name:
            type: string
            nullable: false
            length: 64
            options:
                fixed: false
    lifecycleCallbacks: {  }
